In [1]:
import numpy as np
import sys
sys.path.insert(0,'../')
!cd ../../;make -j12;cd python/test_deform_conv/
import caffe
print caffe

AR -o .build_release/lib/libcaffe.a
<module 'caffe' from '../caffe/__init__.py'>


In [2]:
proto_str="""
input: "matrix"
input_dim: 1
input_dim: 8
input_dim: 2
input_dim: 2
layer{
    name: "offset"
    type: "TransformOffset"
    bottom: "matrix"
    top: "offset"
    transform_offset_param{
        num_output: 8
    }
}
"""
proto_file=open('trans_offset.prototxt','w')
proto_file.write(proto_str)
proto_file.close()

In [3]:
caffe.set_mode_gpu()
net = caffe.Net('trans_offset.prototxt', caffe.TEST)

In [4]:
matrix=net.blobs['matrix'].data
offset=net.blobs['offset'].data
print 'matrix.shape:',matrix.shape
print 'offset.shape:',offset.shape

matrix.shape: (1, 8, 2, 2)
offset.shape: (1, 8, 2, 2)


In [7]:
T = np.array([1, 0, 0,
              0, 1, 0,
              0, 0])
temp = np.tile(T, (matrix.shape[0], matrix.shape[2], matrix.shape[3], 1))
temp = temp.transpose(0, 3, 1, 2)
matrix[:] = temp
# data[:] = np.array([[[ [ 1, 1, 1, 1],
#                        [ 1, 1, 1, 1],
#                        [ 1, 1, 1, 1],
#                        [ 1, 1, 1, 1]]]])
# dweight[:]=np.array([[[ [ 1, 1],
#                        [ 1,1]]]])
print net.blobs['matrix'].data

[[[[ 1.  1.]
   [ 1.  1.]]

  [[ 0.  0.]
   [ 0.  0.]]

  [[ 0.  0.]
   [ 0.  0.]]

  [[ 0.  0.]
   [ 0.  0.]]

  [[ 1.  1.]
   [ 1.  1.]]

  [[ 0.  0.]
   [ 0.  0.]]

  [[ 0.  0.]
   [ 0.  0.]]

  [[ 0.  0.]
   [ 0.  0.]]]]


In [8]:
net.forward()

{'offset': array([[[[-0.5, -0.5],
          [-0.5, -0.5]],
 
         [[-0.5, -0.5],
          [-0.5, -0.5]],
 
         [[-0.5, -0.5],
          [-0.5, -0.5]],
 
         [[ 0.5,  0.5],
          [ 0.5,  0.5]],
 
         [[ 0.5,  0.5],
          [ 0.5,  0.5]],
 
         [[-0.5, -0.5],
          [-0.5, -0.5]],
 
         [[ 0.5,  0.5],
          [ 0.5,  0.5]],
 
         [[ 0.5,  0.5],
          [ 0.5,  0.5]]]], dtype=float32)}