In [1]:
import numpy as np
import mxnet as mx
print mx

<module 'mxnet' from '/home/liming/project/mxnet/python/mxnet/__init__.py'>


In [8]:
N, C, H, W =  (1, 2, 3, 4)
np.random.seed(0)
input_data = np.random.rand(N, C, H, W)
input_offset = np.random.rand(N, 18, H, W)
input_weight = np.random.normal(0, 0.001, (C, C, 3, 3))
input_bias = np.zeros(C)
print input_data

[[[[ 0.5488135   0.71518937  0.60276338  0.54488318]
   [ 0.4236548   0.64589411  0.43758721  0.891773  ]
   [ 0.96366276  0.38344152  0.79172504  0.52889492]]

  [[ 0.56804456  0.92559664  0.07103606  0.0871293 ]
   [ 0.0202184   0.83261985  0.77815675  0.87001215]
   [ 0.97861834  0.79915856  0.46147936  0.78052918]]]]


In [9]:
im_data_var = mx.symbol.Variable(name="im_data")
offset_data_var = mx.symbol.Variable(name="offset_data")
weight_var = mx.symbol.Variable(name="weight")
bias_var = mx.symbol.Variable(name="bias")
op = mx.sym.contrib.DeformableConvolution(name='test_op', data=im_data_var,
                                          offset=offset_data_var,
                                          weight=weight_var, bias=bias_var,
                                          num_filter=C, pad=1,
                                          kernel=(3, 3), stride=(1, 1), dilate=1,
                                          num_deformable_group=1)
context = mx.gpu(0)
ex = op.bind(ctx=context, args={'im_data' : mx.nd.array(input_data, context),
                                'offset_data' : mx.nd.array(input_offset, context),
                               'weight': mx.nd.array(input_weight, context),
                               'bias': mx.nd.array(input_bias, context)})
# ex = op.bind(ctx=context, args={'im_data' : mx.nd.array(input_data, context),
#                                'weight': mx.nd.array(input_weight, context),
#                                'bias': mx.nd.array(input_bias, context)})
y = ex.forward()
print y[0]


[[[[  1.49604969e-03   2.18806020e-03   3.34350765e-03   1.43301091e-03]
   [  3.01993266e-03   2.28476804e-03   2.77834246e-03   2.22456804e-03]
   [  2.56538996e-03   2.52053351e-03   2.60284822e-03   2.72818282e-03]]

  [[  2.18065968e-03   1.57228019e-03   6.88405242e-04   2.15546694e-03]
   [  5.00564929e-04   6.68772554e-05   1.11989083e-03   8.10382771e-04]
   [  1.43623911e-04  -9.10360308e-04  -1.34000159e-03  -6.47203531e-04]]]]
<NDArray 1x2x3x4 @gpu(0)>


In [4]:
mx.nd.array(input_data, context)


[[[[ 0.54881352  0.71518934  0.60276335  0.54488319]
   [ 0.42365479  0.64589411  0.4375872   0.89177299]
   [ 0.96366274  0.38344151  0.79172504  0.5288949 ]]

  [[ 0.56804454  0.92559665  0.07103606  0.0871293 ]
   [ 0.0202184   0.83261985  0.77815676  0.87001216]
   [ 0.97861832  0.79915857  0.46147937  0.7805292 ]]]]
<NDArray 1x2x3x4 @gpu(0)>